- name: "Install Postgresql"
  yum:
    name: "postgresql"
    state: present   
    
- name: "Start the PostgreSQL service"
  service: 
    name: postgresql
    state: started
    enabled: true

- name: "Get the file for create.sql"
  shell: ls -1 {{ zabbix_server_schema_path }}/create.sq*
  changed_when: False
  register: schema_path